In [3]:
import numpy as np
a = np.array([0,1,2,3])

print(type(a))
print(a)

<class 'numpy.ndarray'>
[0 1 2 3]


In [4]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
import numpy as np

# a = np.array(10)
a = np.array([
                [1,2,3,4],
                [5,6,7,8],
                [9,10,11,12]
            ])

print(a.ndim)
print(a.shape)
print(len(a.shape))
print(a.size)
# print(len(a))


2
(3, 4)
2
12


In [51]:
arr1 = np.zeros((4,2,3), dtype = int)
arr2 = np.ones((4,5), dtype = int)
arr3 = np.eye(5, dtype = int)
arr4 = np.diag([1,2,3,4,5])
arr5 = np.empty((2,3), dtype=int)
arr6 = np.arange(2, 19, 3)
arr7 = np.linspace(2, 10, num = 7)

<h3>Sorting & ArgSort</h3>

In [56]:
arr = np.array([1,4,2,6,77,3,5,77,3,2,6,9,7])
np.sort(arr)

array([ 1,  2,  2,  3,  3,  4,  5,  6,  6,  7,  9, 77, 77])

In [57]:
np.argsort(arr)

array([ 0,  2,  9,  5,  8,  1,  6,  3, 10, 12, 11,  4,  7], dtype=int64)

In [58]:
arr.argsort()

array([ 0,  2,  9,  5,  8,  1,  6,  3, 10, 12, 11,  4,  7], dtype=int64)

<h3>Concatenate, Reshape</h3>

In [66]:
a = np.array([[1,2,3], [4,5,6]])
b = np.array([[7,8,9]])

np.concatenate((a,b), axis = 0)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [67]:
a = np.arange(2,10,2)
a.reshape(2,2)

array([[2, 4],
       [6, 8]])

<h3>Adding New Axis/ Dimensions</h3>

In [69]:
a = np.array([1,2,3,4,5,6])
print(a.shape)
print(a.ndim)

(6,)
1


In [70]:
a2 = a[np.newaxis, :]
# See we are adding new row axis. So, it becomes (1,6)
a2 # it is like a row vector

array([[1, 2, 3, 4, 5, 6]])

In [71]:
a3 = a[ : , np.newaxis]
a3 # Will make it (6,1) shaped.
# It is like a column vector.

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [75]:
# Also does the same thing.
rowVector = np.expand_dims(a, axis = 0)
colVector = np.expand_dims(a, axis = 1)
print(colVector)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


<h3>Condition Based Slicing</h3>

In [76]:
a = np.array([[13,10,2,4],[7,5,12,8],[10,4,7,13]])
a

array([[13, 10,  2,  4],
       [ 7,  5, 12,  8],
       [10,  4,  7, 13]])

In [78]:
(a > 5) & (a < 10)

array([[False, False, False, False],
       [ True, False, False,  True],
       [False, False,  True, False]])

In [79]:
# ---> Now These boolean values can be passed as slicing Condition:
# ---> But the Output is always 1D Array.
mask = (a > 5) & (a < 10)
a[mask]

array([7, 8, 7])

In [80]:
np.nonzero(a < 5)

(array([0, 0, 2], dtype=int64), array([2, 3, 1], dtype=int64))

<h3>Horizontal, Vertical Stack. Horizontal Split</h3>

In [4]:
import numpy as np
a1 = np.array([
                [1,1],
                [2,2]
                ])

a2 = np.array([
                [3,3],
                [4,4]
                ])
# Must be careful about the dimensions while stacking.

In [5]:
np.vstack((a1,a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [6]:
np.hstack((a1,a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [13]:
# We 

x = np.arange(1,25).reshape(2,12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [12]:
# Splitting x into 3 equal arrays. It does not give ndarray. It gives List of same shaped ndarray.
np.hsplit(x, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [14]:
# We can specify split at positions too.
np.hsplit(x, (3,4,7))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7],
        [17, 18, 19]]),
 array([[ 8,  9, 10, 11, 12],
        [20, 21, 22, 23, 24]])]

<h3>View, Copy</h3>

When we are creating/splitting arrays we are creating Shallow copies.

In [26]:
arr = np.arange(10)
b = arr[2:4].copy()

print(b)

b[1] = 20 # Btw we can't do b[2] although we are using views.
arr # See arr is changed. Because b was pinting to same thing in the memory.
# Indexing, Slicing everything returns views only.

[2 3]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
# To bypass this use .copy(). But it actually does shallowcopy only. For deepcopy use "from copy import deepcopy"

<h3>Basic Array Operations</h3>

In [43]:
# ndarray default mode: Element wise operation.
# This happens due to broadcasting.
a = np.arange(2,10)
b = np.arange(5, 15)
print(a)
print(b)
a+b # Will give error bcoz sizes are different.

[2 3 4 5 6 7 8 9]
[ 5  6  7  8  9 10 11 12 13 14]


ValueError: operands could not be broadcast together with shapes (8,) (10,) 

In [42]:
a = np.arange(2,10)
b = np.arange(5, 13)
print(a)
print(b)
print(a+b)
print(a/b)

[2 3 4 5 6 7 8 9]
[ 5  6  7  8  9 10 11 12]
[ 7  9 11 13 15 17 19 21]
[0.4        0.5        0.57142857 0.625      0.66666667 0.7
 0.72727273 0.75      ]


In [55]:
a = np.arange(1, 10)
b = a.reshape((3,3))

print(b)

print(b.sum(axis = 1))
print(b.sum(axis = 0))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[ 6 15 24]
[12 15 18]


In [59]:
a.sum(axis = 0) # Same as a.sum() as a.ndim is 1 only.

45

<h3>Min, Max, Mean, Std, Prod</h3>

<p>Same as sum() we can use these too.</p>
<p>Std is +ve Root(var(x)) Where var(x) = (Sum of (xi - xn)^2)/(n-1)</p>
<p>If we do not give axis, it gives for entire array.</p>
<p>Population Variance = σ2 = ∑ (xi – x̄)2/n</p>
<p>Sample Variance = σ2 = ∑ (xi – x̄)2/(n – 1)</p>

In [63]:
a = np.arange(1, 10)
b = a.reshape((3,3))

print(b)

b.std(axis = 0)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([2.44948974, 2.44948974, 2.44948974])

<h3>Generating Random Numbers</h3>

In [65]:
np.random.randint(2, 9, (3,2)) # Gives 3*2 ndarray having random ints b/w 2 to 9.

array([[8, 3],
       [8, 3],
       [3, 4]])

In [3]:
import numpy as np
# Newer version is rng: random number generator
rng = np.random.default_rng()
rng.integers(5, size = (2,4)) # Gives 2*4 ndarray having random ints b/w 0 to 5.

array([[0, 1, 2, 4],
       [2, 1, 0, 1]], dtype=int64)

In [71]:
rng.integers(2, 9, size = (3,2)) # Same as np.random.randint(2, 9, (3,2))

array([[3, 5],
       [4, 3],
       [5, 6]], dtype=int64)

In [4]:
type(rng)

numpy.random._generator.Generator

<h3> Unique Items, Transforming Matrix, Reverse Array </h3>

In [6]:
a = np.array([11,11,12,13,10,9,6,8,7,6,4])
np.unique(a)

array([ 4,  6,  7,  8,  9, 10, 11, 12, 13])

In [7]:
unique_values, occurance_count = np.unique(a, return_counts=True)
print(unique_values)
print(occurance_count)

[ 4  6  7  8  9 10 11 12 13]
[1 2 1 1 1 1 2 1 1]


<h3> Transposing & Flipping Arrays </h3>

In [16]:
a = np.array([[2,3,5], [4,5,8]])
a.transpose() # Does not change the Array.


array([[2, 4],
       [3, 5],
       [5, 8]])

In [17]:
a.T # Same as a.transpose. Does not change the array.

array([[2, 4],
       [3, 5],
       [5, 8]])

In [18]:
a

array([[2, 3, 5],
       [4, 5, 8]])

In [19]:
a = np.array([[2,3,5], [4,5,8]])
np.flip(a)

array([[8, 5, 4],
       [5, 3, 2]])

In [20]:
np.flip(a, axis=0) # only Flips along the rows.

array([[4, 5, 8],
       [2, 3, 5]])

In [21]:
np.flip(a, axis = 1)

array([[5, 3, 2],
       [8, 5, 4]])

<h3>Very Important: Flatten & Ravel</h3>
These are very important in ANN, CNN etc. Converting Multi Dimensional Array to
1-D Array or vise versa.

In [23]:
a = np.array([[2,3,5], [4,5,8], [11,12,13]])
a.flatten()


array([ 2,  3,  5,  4,  5,  8, 11, 12, 13])

In [24]:
a.ravel()

array([ 2,  3,  5,  4,  5,  8, 11, 12, 13])

In [28]:
# So, we may think both are same. But actually,
# if we assign a1 and a2 to them, we will see that ravel() uses the
# concept of view. So, change in a2 will get reflected in original arr a.
# In case of a1 = a.flatten() it will not happen.
a2 = a.ravel()
a2[3] = 100
a

array([[  2,   3,   5],
       [100,   5,   8],
       [ 11,  12,  13]])

In [29]:
# Using help we can see documentation of a method.
help(max)

Help on built-in function max in module builtins:

max(...)
    max(iterable, *[, default=obj, key=func]) -> value
    max(arg1, arg2, *args, *[, key=func]) -> value
    
    With a single iterable argument, return its biggest item. The
    default keyword-only argument specifies an object to return if
    the provided iterable is empty.
    With two or more arguments, return the largest argument.



In [30]:
# In Numpy, mathematical formula can be used very easily.
# In Supervised learning, we use MeanSquareErrorwhich is readily
# available in NumPy. We can save & load numpy objects too.
# Pandas in built on top of NumPy.