In [3]:
import numpy as np
a = np.array([0,1,2,3])

print(type(a))
print(a)

<class 'numpy.ndarray'>
[0 1 2 3]


In [4]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
import numpy as np

# a = np.array(10)
a = np.array([
                [1,2,3,4],
                [5,6,7,8],
                [9,10,11,12]
            ])

print(a.ndim)
print(a.shape)
print(len(a.shape))
print(a.size)
# print(len(a))


2
(3, 4)
2
12


In [51]:
arr1 = np.zeros((4,2,3), dtype = int)
arr2 = np.ones((4,5), dtype = int)
arr3 = np.eye(5, dtype = int)
arr4 = np.diag([1,2,3,4,5])
arr5 = np.empty((2,3), dtype=int)
arr6 = np.arange(2, 19, 3)
arr7 = np.linspace(2, 10, num = 7)

<h3>Sorting & ArgSort</h3>

In [56]:
arr = np.array([1,4,2,6,77,3,5,77,3,2,6,9,7])
np.sort(arr)

array([ 1,  2,  2,  3,  3,  4,  5,  6,  6,  7,  9, 77, 77])

In [57]:
np.argsort(arr)

array([ 0,  2,  9,  5,  8,  1,  6,  3, 10, 12, 11,  4,  7], dtype=int64)

In [58]:
arr.argsort()

array([ 0,  2,  9,  5,  8,  1,  6,  3, 10, 12, 11,  4,  7], dtype=int64)

<h3>Concatenate, Reshape</h3>

In [66]:
a = np.array([[1,2,3], [4,5,6]])
b = np.array([[7,8,9]])

np.concatenate((a,b), axis = 0)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [67]:
a = np.arange(2,10,2)
a.reshape(2,2)

array([[2, 4],
       [6, 8]])

<h3>Adding New Axis/ Dimensions</h3>

In [69]:
a = np.array([1,2,3,4,5,6])
print(a.shape)
print(a.ndim)

(6,)
1


In [70]:
a2 = a[np.newaxis, :]
# See we are adding new row axis. So, it becomes (1,6)
a2 # it is like a row vector

array([[1, 2, 3, 4, 5, 6]])

In [71]:
a3 = a[ : , np.newaxis]
a3 # Will make it (6,1) shaped.
# It is like a column vector.

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [75]:
# Also does the same thing.
rowVector = np.expand_dims(a, axis = 0)
colVector = np.expand_dims(a, axis = 1)
print(colVector)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


<h3>Condition Based Slicing</h3>

In [76]:
a = np.array([[13,10,2,4],[7,5,12,8],[10,4,7,13]])
a

array([[13, 10,  2,  4],
       [ 7,  5, 12,  8],
       [10,  4,  7, 13]])

In [78]:
(a > 5) & (a < 10)

array([[False, False, False, False],
       [ True, False, False,  True],
       [False, False,  True, False]])

In [79]:
# ---> Now These boolean values can be passed as slicing Condition:
# ---> But the Output is always 1D Array.
mask = (a > 5) & (a < 10)
a[mask]

array([7, 8, 7])

In [80]:
np.nonzero(a < 5)

(array([0, 0, 2], dtype=int64), array([2, 3, 1], dtype=int64))

<h3> Horizontal, Vertical Stack, Horizontal Split </h3>